language: node_js
sudo: required
node_js:
  - '7'
  - '6'
addons:
  apt:
    packages:
      - xvfb
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cachegi
before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
install:
  - npm install
  - cd packages/create-elm-app
  - npm install
  - npm link
  - cd ..
script: npm test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
